const test=require('node:test'),assert=require('node:assert/strict'),E=require('../js/growth-evidence'),G=require('../js/growth-sync'),R=require('../js/growth-records');
const ctx={uid:'u',familyId:'f',childKey:'c',childCode:'CODE'},scope=JSON.stringify(['u','CODE']);
const record={id:'r',scope,group:'academy',activity:'리드101',title:'원문',text:'원문 메시지',date:'2026-10-07',createdAt:1};
function setup(){let context=ctx,fail=null;const docs=new Map();const adapter={list:async()=>{if(fail)throw fail;return [...docs].map(([id,d])=>({id,...d})).filter(d=>d.childKey===context.childKey)},transaction:async(p,fn)=>{const id=p.split('/').at(-1),d=fn(docs.get(id)||null);if(d)docs.set(id,d);return d||docs.get(id)}};return {api:G.create({getContext:()=>context,adapter,structuredWrites:true,now:()=>20}),docs,switch:x=>context=x,fail:e=>fail=e};}
const metadata={experienceId:'experience-a',experienceStatus:'unknown',occurredDate:null,datePrecision:'unknown',institutionRef:{namespace:'family',localId:'read-pangyo',label:'리드101 판교점',classLabel:null},relationshipStatus:'unknown',evidenceEntries:[{evidenceId:'original',evidenceVersion:1,kind:'artifact',source:{author:{role:'unknown'},providerType:'academy'},performed:null,outcome:null,feedback:null,originalText:'보존'}]};
test('optional fields survive prepare/local serialization without inferring experience date',()=>{const p=R.prepare({...record,...metadata},scope,1);assert.deepEqual(E.fields(JSON.parse(JSON.stringify(p))),metadata);assert.equal(E.project(p,ctx).occurredDate,null);assert.equal(E.fields(record).evidenceEntries,undefined)});
test('server round trip and title edits preserve evidence, activity and real registration date',async()=>{const f=setup(),saved=await f.api.save({...record,...metadata});assert.equal(saved.schemaVersion,2);assert.equal(saved.registeredAt,20);const edit=await f.api.save({...saved,title:'새 제목'});assert.deepEqual(E.fields(edit),metadata);assert.equal(edit.activityId,saved.activityId);assert.equal(edit.revision,2);});
test('references invalidate on edits, correction, deletion and child switches',()=>{const r={...record,...metadata,revision:1};const ref=E.reference(r,ctx,'original');assert.equal(E.resolve(r,ref,ctx).status,'ok');assert.equal(E.resolve({...r,revision:2},ref,ctx).status,'stale');assert.equal(E.resolve({...r,evidenceEntries:[...r.evidenceEntries,{evidenceId:'corrected',evidenceVersion:1,supersedes:'original'}]},ref,ctx).status,'stale');assert.equal(E.resolve({...r,deletedAt:1},ref,ctx).status,'missing');assert.equal(E.resolve(r,ref,{...ctx,childKey:'other'}).status,'context_changed');});
test('education reader separates empty, failed, permission denied and stale context',async()=>{const f=setup();assert.equal((await f.api.related(scope)).status,'empty');await f.api.save({...record,...metadata});const rows=await f.api.related(scope);assert.equal(rows.status,'ok');f.switch({...ctx,childKey:'other',childCode:'OTHER'});assert.equal((await f.api.related(scope)).status,'context_changed');f.switch(ctx);f.fail(Object.assign(Error('blocked'),{code:'permission-denied'}));assert.equal((await f.api.resolveReference(scope,E.reference(rows.items[0].original,ctx,'original'))).status,'permission_denied');f.fail(Error('network'));assert.equal((await f.api.related(scope)).status,'failed');});
test('same experience counts once, unconfirmed and scheduled-only records are excluded',()=>{const r={...record,...metadata,experienceStatus:'occurred',relationshipStatus:'confirmed'};assert.deepEqual(E.experiences([r,{...r,id:'r2'},{...r,experienceStatus:'planned'},{...record,deletedAt:1}]),{confirmedExperienceCount:1,unconfirmedRecordCount:1});});
test('institution mapping requires confirmation, and default server writes reject unsupported metadata',async()=>{assert.throws(()=>E.mapActivity({activityId:'a',childKey:'c'}),/확인/);assert.equal(E.mapActivity({activityId:'a',childKey:'c',confirmed:true,linkedScheduleIds:['영도']} ).institutionRef,null);const api=G.create({getContext:()=>ctx,adapter:{}});await assert.rejects(api.save({...record,...metadata}),/규칙/);});
test('v1 import fingerprint remains compatible with already uploaded phone records',async()=>{const {createHash}=require('node:crypto'),hash=async s=>createHash('sha256').update(s).digest('hex'),id='import_'+await hash(record.scope+'\u0000'+record.id);const fp=await hash(JSON.stringify([record.group,record.activity,record.title,record.text,record.date,'']));const api=G.create({getContext:()=>ctx,hash,adapter:{list:async()=>[{id,importFingerprint:fp}]}});assert.deepEqual(await api.pendingLocal([record],scope),[]);});
test('reader avoids image downloads in lists, and revision/delete revalidation rejects old refs',async()=>{const f=setup(),saved=await f.api.save({...record,...metadata});const ref=E.reference(saved,ctx,'original');assert.equal((await f.api.resolveReference(scope,ref)).status,'ok');await f.api.save({...saved,title:'정정'});assert.equal((await f.api.resolveReference(scope,ref)).status,'stale');const d=f.docs.get('r');d.deletedAt=1;assert.equal((await f.api.resolveReference(scope,ref)).status,'missing');});
test('prepare keeps stable activity ID during existing UI title edit and optional extension omission',()=>{const existing={...record,...metadata,activityId:'stable',revision:4};const item={...existing,...R.prepare({id:existing.id,group:existing.group,activity:'이름 변경',title:'제목 변경',text:existing.text,date:existing.date},scope,1)};assert.equal(item.activityId,'stable');assert.deepEqual(E.fields(item),metadata);});
test('missing authentication returns permission status rather than empty data',async()=>{const api=G.create({getContext:()=>({})});assert.equal((await api.related(scope)).status,'permission_denied');assert.equal((await api.resolveReference(scope,{})).status,'permission_denied');});
