const test=require('node:test'),assert=require('node:assert/strict'),{create}=require('../js/growth-sync');
const {createHash,webcrypto}=require('node:crypto');global.crypto=webcrypto;
const hash=async s=>createHash('sha256').update(s).digest('hex');
function fixture(){let ctx={uid:'u1',familyId:'h1',childKey:'c1',childCode:'ABC123'};const docs=new Map(),images=new Map();let uploads=0;
 const adapter={list:async(p,key)=>[...docs].filter(([path,d])=>path.startsWith(p+'/')&&d.childKey===key).map(([p,d])=>({id:p.split('/').at(-1),...d})),transaction:async(p,f)=>{const d=f(docs.get(p)||null);if(d)docs.set(p,d);return d||docs.get(p);},upload:async(p,b)=>{uploads++;images.set(p,b);},image:async p=>{if(!images.has(p))throw Error('image missing');return images.get(p);}};
 return {api:create({getContext:()=>ctx,adapter,hash,now:()=>10}),docs,images,context:x=>ctx=x,uploads:()=>uploads};}
const record=(extra={})=>({id:'r1',scope:JSON.stringify(['u1','ABC123']),group:'academy',activity:'피아노',title:'끝까지 연주했어요',text:'선생님 메시지',date:'2026-10-08',createdAt:1,...extra});
test('family read selects one child and updates use revisions; stale edits fail',async()=>{const f=fixture(),saved=await f.api.save(record());assert.equal(saved.revision,1);const edit=await f.api.save({...saved,title:'새 제목'});assert.equal(edit.revision,2);await assert.rejects(f.api.save({...saved,title:'옛 수정'}),/가족이/);f.docs.set('households/h1/growthRecords/other',{...f.docs.values().next().value,childKey:'c2'});assert.equal((await f.api.read(record().scope)).length,1);});
test('import retries are idempotent and never replace newer family edits',async()=>{const f=fixture(),r=record();let res=await f.api.importLocal([r],r.scope);assert.equal(res.done,1);const s=(await f.api.read(r.scope))[0];await f.api.save({...s,title:'가족 수정'});res=await f.api.importLocal([r],r.scope);assert.equal(res.done,1);assert.equal(f.docs.size,1);assert.equal((await f.api.read(r.scope))[0].title,'가족 수정');await assert.rejects(f.api.importLocal([record({scope:'local'})],'local'),/계정·아이/);});
test('attachment upload is read back and preserved on text-only edits; replacement works',async()=>{const f=fixture(),r=record({image:new Blob(['image'],{type:'image/png'})});const s=await f.api.save(r);assert.equal(s.image.size,5);assert.equal(f.uploads(),1);const e=await f.api.save({...s,title:'수정'});assert.equal(f.uploads(),1);const replaced=await f.api.save({...e,image:new Blob(['new'],{type:'image/png'}),imageChanged:true});assert.equal(replaced.image.size,3);assert.equal(f.uploads(),2);});
test('failed attachments stay visible as errors without reporting upload success',async()=>{const f=fixture(),s=await f.api.save(record({image:new Blob(['image'],{type:'image/png'})}));f.images.clear();const rows=await f.api.read(s.scope);assert.equal(rows[0].imageError,true);const edit=await f.api.save({...rows[0],title:'텍스트만 수정'});assert.equal(edit.attachment.storagePath,s.attachment.storagePath);});
test('upload verification failure never commits a record',async()=>{const docs=new Map();let commits=0;const api=create({getContext:()=>({uid:'u1',familyId:'h1',childKey:'c1'}),hash,adapter:{upload:async()=>{},image:async()=>new Blob(['wrong'],{type:'image/png'}),transaction:async()=>{commits++;}}});await assert.rejects(api.save(record({image:new Blob(['right-image'],{type:'image/png'})})),/アップ|사진 업로드/);assert.equal(commits,0);});
test('switching family during image upload stops the document write',async()=>{let ctx={uid:'u1',familyId:'h1',childKey:'c1'},commits=0;const blob=new Blob(['image'],{type:'image/png'});const api=create({getContext:()=>ctx,hash,adapter:{upload:async()=>{ctx={...ctx,familyId:'h2'};},image:async()=>blob,transaction:async()=>{commits++;}}});await assert.rejects(api.save(record({image:blob})),/변경/);assert.equal(commits,0);});
test('completed imports stay out of the import prompt, but changed local originals are reported',async()=>{const f=fixture(),r=record();assert.equal((await f.api.pendingLocal([r],r.scope)).length,1);await f.api.importLocal([r],r.scope);assert.equal((await f.api.pendingLocal([r],r.scope)).length,0);assert.equal((await f.api.pendingLocal([{...r,title:'기기에서 변경'}],r.scope)).length,1);});
